stages:
  - plan
  - upload
  - apply
  - destroy

#region plan
review-plan:
  image:
    name: hashicorp/terraform:0.14.2
    entrypoint: ["/bin/sh", "-c"]
  stage: plan
  script:
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}  
  - mkdir main
  - cd main
  - terraform init
  - terraform plan -out terraform_plan_main
  artifacts:
    reports:
      terraform: main/terraform_plan_main
  only:
    changes:
      - modules/
      - main/
      - .gitlab-ci.yml
#endregion plan

#region apply
review-apply:
  image:
    name: hashicorp/terraform:0.14.2
    entrypoint: ["/bin/sh", "-c"]
  stage: apply
  before_script:
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}  
    - cd main/
    - terraform init
  script:
    - terraform plan  -out terraform_plan_main
    - terraform apply -input terraform_plan_main
#endregion

#region reviewapp-destroy
reviewapp-destroy:
  image:
    name: hashicorp/terraform:0.14.2
    entrypoint: ["/bin/sh", "-c"]
  stage: destroy
  before_script:
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}  
    - cd main/
    - terraform init
  script:
    - terraform destroy -auto-approve
  when: manual
