stages:
  - init
  - plan
  - apply
  - destroy

image:
  name: hashicorp/terraform:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


before_script:
  - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
  - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
  - export AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION"
  - rm -rf .terraform
  - terraform --version

init:
  stage: init
  script:
    - terraform init -backend-config="bucket=$BUCKET_NAME" -backend-config="key=$ENVIRONMENT_NAME/$FILENAME"
    - terraform validate
  when: manual


plan: 
  stage: plan
  script: 
    - terraform plan -out "planfile" -var="environment=$ENVIRONMENT_NAME" -var="public_key=$PUBLIC_KEY"
  dependencies:
    - init
  artifacts:
    paths:
      - planfile
  when: manual

apply: 
  stage: apply
  script: 
    - terraform apply --auto-approve -input=false "planfile" -var="environment=$ENVIRONMENT_NAME" -var="public_key=$PUBLIC_KEY"
  dependencies: 
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy --auto-approve -var="environment=$ENVIRONMENT_NAME" -var="public_key=$PUBLIC_KEY"
  dependencies: 
    - apply 
  when: manual