stages:
  - validate
  - plan
  - apply
  - destroy

image:
  name: hashicorp/terraform:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables: 
  AWS_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  AWS_PROFILE: ${AWS_PROFILE}

before_script:
    - rm -rf .terraform
    - terraform --version
    - terraform init

validate:
  stage: validate
  script: 
    - terraform validate

plan: 
  stage: plan
  script: 
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply: 
  stage: apply
  script: 
    - terraform apply --auto-approve -input=false "planfile"
  dependencies: 
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy --auto-approve
  dependencies: 
    - apply 
  when: manual
