---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  vars:
    ansible_ssh_private_key_file: $PRIVATE_KEY

  tasks:
    - name: Install jq, JSON parser
      yum: 
        name: jq
        state: present
