---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_ssh_private_key_file: $PRIVATE_KEY
  tasks:
    - name: Install Git client
      yum: 
        name: git
        state: present
    - name: Install httpd
      yum:
        name: httpd
        state: present
    - name: Start and Enable Apache
      service: 
        name: httpd
        state: started
        enabled: yes       